### ISSUE TITLE
Enable GitHub Service Hook for Packagist

### ISSUE THREAD

**Issue by PhoneixS** [dmitrirussu/php-sepa-xml-generator#16]
I don't know if you have enabled it, but it is very recommended so it is updated when you push instead of one time per day (from https://packagist.org/about).

To activate the hook, you can do the following (from https://packagist.org/profile/):

> GitHub Service Hook
> 
> Enabling the Packagist service hook ensures that your package will always be updated instantly when you push to GitHub. To do so you can go to your GitHub repository, click the "Settings" button, then "Webhooks & Services". Add a "Packagist" service, and configure it with your API token (see above), plus your Packagist username. Check the "Active" box and submit the form. You can then hit the "Test Service" button to trigger it and check if Packagist removes the warning about the package not being auto-updated.

I'm saying this because your last update (93d8eb7) still doesn't appear in packagist.

**Comment by PhoneixS** [comment]
I think this can be closed as it seems to be updating ok

**Comment by PhoneixS** [comment]
I think that isn't updated after a push again. Maybe you need to revise the hook or the GitHub Service for Packagist.

**Comment by dmitrirussu** [comment]
hi @PhoneixS , sorry for delay answer, i would appreciate if you can manage to contribute with some fixes, I'm out of time to contribute actively for current package.
