### ISSUE TITLE
createXMLCreditTransfertTransaction returns null

### ISSUE THREAD

**Issue by nodexii** [dmitrirussu/php-sepa-xml-generator#20]
XMLGeneratorFactory::createXMLPaymentInfo()->createXMLCreditTransfertTransaction
returns null.
Seems credit is not fully implemented yet?

**Comment by dmitrirussu** [comment]
Is strange, it was done and tested, I will try to check.

**Comment by dmitrirussu** [comment]
I did some updates you can check unit Test for tests/XMLGeneratorFactoryTest.php

Method ->  testCreateCreditTransferXmlFile
