### ISSUE TITLE
CreationDateTime is not in 24-hour format

### ISSUE THREAD

**Issue by mstra001** [dmitrirussu/php-sepa-xml-generator#21]
In [lib/SEPA/GroupHeader.php, line 111](https://github.com/dmitrirussu/php-sepa-xml-generator/blob/9357112220dd73d99842c5521e374a07f9dc52b7/lib/SEPA/GroupHeader.php#L111)

you could replace this

```
$this->CreationDateTime = str_replace(' ', 'T', $date->format('Y-m-d h:i:s'));
```

with this line

```
$this->CreationDateTime = $date->format('Y-m-d\TH:i:s');
```

**Comment by dmitrirussu** [comment]
Thanks, was datetime format was updated
