### ISSUE TITLE
about the structure of SEPA Credit Transfer

### ISSUE THREAD

**Issue by LioCodebio** [dmitrirussu/php-sepa-xml-generator#27]
Having to Generate SEPA Credit Transfer's XMLs, I ran into some structure issues when I tried to validate them:
- CstmrDrctDbtInitn not recognised, I had to replace this tag by pain.001.001.02,
- BtchBookg part of GrpHdr and not of  PmtInf,
- NbOfTxs and  CtrlSum shouldn't be part of  PmtInf,
- Grpg mandatory (with the value of MIXD) (inside GrpHdr)
- order of tags in GrpHdr: 
     MsgId
     CreDtTm
     BtchBookg
     NbOfTxs
     CtrlSum
     Grpg
     InitgPty     >     Nm
- SeqTp Not recognised, and besides I couldn't find it in the iso-20022.
- CreditInvoice not mandatory, but you check in your code its existence (SEPA/CreditTransferTransactions.php), creating an empty CdtTrfTxInf when a value is not given.

Finally, I found very usefull the possibility to save the xml generated as a text, by modifying XMLGenerator::save() as such:
         /**
	 * Save Xml File
         * @param string $stream
	 * @param null $fileName
	 * @return bool|mixed
	 */
	public function save($stream, $fileName = null) {
            $dom = new \DOMDocument('1.0');
            $dom->preserveWhiteSpace = false;
            $dom->formatOutput = true;

            if ( !$this->xml->children() ) {

                    $this->generateMessages();
                    $dom->loadXML($this->xml->asXML());
            }
            else {

                    $dom->loadXML($this->getGeneratedXml());
            }
            if ( $stream == "file" && $fileName ) {
                return ($dom->save($fileName) ? true : false);
            }
            elseif ($stream == "text")
                return $dom->saveXML ();
            return $this;
	}

**Comment by dmitrirussu** [comment]
Thanks for your request I have append all changes for credit transfer now it correspond with  documentation.
