### ISSUE TITLE
Bic Optional

### ISSUE THREAD

**Issue by roke22** [dmitrirussu/php-sepa-xml-generator#30]
Hello,

In the example you said that the Debit Bic is optional ( ->setDebitBIC('AABAFI22') //Optional ) but if we leave it blank we get in the xml this:

<DbtrAgt><FinInstnId><Othr><Id>NOTPROVIDED</Id></Othr></FinInstnId></DbtrAgt>

How to make really optional?

Best Regards.

**Comment by RamonSmit** [comment]
Hi, 

For as far as I know, some banks require the tag and others don't. 
This is the expected behavior of this script.

You don't need to set the BIC code, but then the script will put ```NOTPROVIDED``` in the XML for compatibility. 

Best Regards, 
Ramon

**Comment by ericsala** [comment]
Is there any method to obtain the BIC code using IBAN? If there is no method with this library do you use any API or service to generate it? Thank you!
