### ISSUE TITLE
Version 1.0.8 not available on packagist

### ISSUE THREAD

**Issue by Messenbrink** [dmitrirussu/php-sepa-xml-generator#31]
Hi, seems like `composer require dmitrirussu/php-sepa-xml-generator` will install version 1.0.7 instead of the advertised version 1.0.8. When will you release the latest version on packagist?

**Comment by oleics** [comment]
@dmitrirussu Can you please update the master to a new version and announce that new version to packagist?

**Comment by Brah0um** [comment]
@dmitrirussu UP

Can you please create a new tag for the new methods that you implemented ?
IMHO, it is not a good practice to use `dev-master` in the `composer.json`

**Comment by dmitrirussu** [comment]
@Brah0um @oleics @Messenbrink , done

**Comment by oleics** [comment]
tnx
