### ISSUE TITLE
Don't use `unset($this)`

### ISSUE THREAD

**Issue by PhoneixS** [dmitrirussu/php-sepa-xml-generator#32]
I have an error `PHP Fatal error:  Cannot unset $this` in php7.1 with the XMLGenerator because it has a method like:

```
public function __destruct() {
      unset($this);
}
```

From the php documentation of unset you can read:

>     Note:
> 
>     It is not possible to unset $this inside an object method since PHP 5.

Before php7 it doesn't hurt but now it complains about it. I think it could be removed without problems as $this variable is removed automatically when you go out of context.

**Comment by dmitrirussu** [comment]
I did an update for that
