### ISSUE TITLE
Severity: Error --> Class SEPA\XMLGenerator contains 1 abstract method

### ISSUE THREAD

**Issue by itemvirtual** [dmitrirussu/php-sepa-xml-generator#34]
Hi,
I can't use with PHP 5.6, it returns this error:
ERROR - 2019-02-18 16:08:33 --> Severity: Error --> Class SEPA\XMLGenerator contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (SEPA\XMLGeneratorInterface::__destruct) /var/www/rebill.net/admin/vendor/dmitrirussu/php-sepa-xml-generator/lib/SEPA/XMLGenerator.php 222

Could you help me to solve it?

Thanks,
Fidel

**Comment by dmitrirussu** [comment]
done fix for thanks
