### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mbardelmeijer** [dmitrirussu/php-sepa-xml-generator#36]
Hey @dmitrirussu, could you please release a new version? We're running into issue https://github.com/dmitrirussu/php-sepa-xml-generator/issues/34 (abstract method implementation) which is fixed on master but not available on packagist.

Thanks!

**Comment by PhoneixS** [comment]
You can use the 1.0.8.x-dev branch release. For example with `composer require dmitrirussu/php-sepa-xml-generator 1.0.8.x-dev`.

**Comment by dmitrirussu** [comment]
done, Thanks
